# frozen_string_literal: true

source "https://rubygems.org"

gem 'sinatra'
gem 'uri'
gem 'rubysl-net-http', '~> 2.0', '>= 2.0.4'
gem 'openssl', '~> 2.2'
gem 'geocoder'
gem 'json'
gem 'sinatra-cross_origin', '~> 0.4.0'
